Tests: default to test-base because that's what i use
I'm sick of typing --base-dir test-base

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -1,20 +1,19 @@
 #!/usr/bin/env bash
 
-SetBaseDir() {
-  BASEDIR=$1
-  if [[ ! $BASEDIR = /* ]]; then
-    # Relative
-    BASEDIR=$(pwd)/${BASEDIR}
+AbsDirOf() {
+  if [ -d "$1" ]; then
+    ( cd "$1" && pwd -P )
+  else
+    ( cd $(dirname "$1") && pwd -P )
   fi
 }
 
-SetBaseDir $(dirname $0)
+BASEDIR=$(AbsDirOf "$0")/test-base
 INSTALL=0
 UPDATE=0
 INSTALLER_ARGS=''
 RUN_VIM="vim -N --clean --not-a-term"
 RUN_TEST="${RUN_VIM} -S lib/run_test.vim"
-BASEDIR_CMD='py3 pass'
 
 # 1 is stdout
 out_fd=1
@@ -23,9 +22,8 @@ while [ -n "$1" ]; do
   case "$1" in
     "--basedir"|"--base-dir"|"--test-base")
       shift
-      SetBaseDir $1
+      BASEDIR=$(AbsDirOf "$1")
       shift
-      BASEDIR_CMD="let g:vimspector_base_dir='${BASEDIR}'"
       ;;
     "--install")
       INSTALL=1
@@ -87,6 +85,26 @@ if [ "${out_fd}" = "1" ]; then
   exec 3>&1
 fi
 
+if [ -z "$VIMSPECTOR_MIMODE" ]; then
+  if which lldb >/dev/null 2>&1; then
+    export VIMSPECTOR_MIMODE=lldb
+  elif which gdb >/dev/null 2>&1; then
+    export VIMSPECTOR_MIMODE=gdb
+  else
+    echo "Couldn't guess VIMSPECTOR_MIMODE. Need lldb or gdb in path"
+    exit 1
+  fi
+fi
+
+BASEDIR_CMD="let g:vimspector_base_dir='${BASEDIR}'"
+
+echo "Testing with:"
+echo " * VIMSPECTOR_MIMODE=$VIMSPECTOR_MIMODE"
+echo " * RUN_VIM=$RUN_VIM"
+echo " * RUN_TEST=$RUN_TEST"
+echo " * BASEDIR=$BASEDIR"
+echo " * BASEDIR_CMD=$BASEDIR_CMD"
+
 if [ "$INSTALL" = "1" ] || [ "$INSTALL" = "script" ]; then
   if ! python3 $(dirname $0)/install_gadget.py \
                --basedir ${BASEDIR} \
@@ -121,24 +139,6 @@ if [ "$UPDATE" = "1" ]; then
   fi
 fi
 
-
-if [ -z "$VIMSPECTOR_MIMODE" ]; then
-  if which lldb >/dev/null 2>&1; then
-    export VIMSPECTOR_MIMODE=lldb
-  elif which gdb >/dev/null 2>&1; then
-    export VIMSPECTOR_MIMODE=gdb
-  else
-    echo "Couldn't guess VIMSPECTOR_MIMODE. Need lldb or gdb in path"
-    exit 1
-  fi
-fi
-
-echo "Testing with:"
-echo " * VIMSPECTOR_MIMODE=$VIMSPECTOR_MIMODE"
-echo " * RUN_VIM=$RUN_VIM"
-echo " * RUN_TEST=$RUN_TEST"
-echo " * BASEDIR=$BASEDIR"
-echo " * BASEDIR_CMD=$BASEDIR_CMD"
 
 
 echo "%SETUP - Building test programs..."
