Test with latest vim on macos because i hate github actions

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -103,6 +103,21 @@ if [ "${out_fd}" = "1" ]; then
   exec 3>&1
 fi
 
+# Basic pre-flight check that vim and python work
+# ffs neovim https://github.com/neovim/neovim/issues/14438
+if ${RUN_VIM} -u support/test_python3.vim .fail; then
+  rm -f .fail
+  echo "$VIM_EXE appears to have working python3 support. Let's go..."
+else
+  cat .fail
+  rm -f .fail
+  echo ""
+  echo ""
+  echo "ERROR: $VIM_EXE does not appear to have working python3 support."
+  echo "ERROR: Cannot continue"
+  exit 1
+fi
+
 if [ -z "$VIMSPECTOR_MIMODE" ]; then
   if which lldb >/dev/null 2>&1; then
     export VIMSPECTOR_MIMODE=lldb
